#!/bin/bash

set -e
set -u

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images from templates.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        sed -e "s/%%GARRYSMOD_BETA%%/$GARRYSMOD_BETA/" \
            Dockerfile.template >Dockerfile

        if [[ "${GARRYSMOD_BETA}" == "NONE" ]]; then
            docker \
                build -t "quay.io/rbreslow/garrysmodds:slim" .
        else
            docker \
                build -t "quay.io/rbreslow/garrysmodds:${GARRYSMOD_BETA}-slim" .
        fi

        docker images
    fi
fi
